name: Deploy AWS Lambda

on:
  push:
    branches:
      - webScrapeAlgo  # Change to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13' 

      - name: Setup AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Dependencies
        run: |
          cd src  # Change to your function directory
          pip install -r requirements.txt -t .

      - name: Package Lambda Function
        run: |
          cd src
          zip -r lambda_function.zip .

      - name: Upload to S3
        run: |
          aws s3 cp ./src/lambda_function.zip s3://auto-trading-bucket/1790ffe7-7b30-4e22-a488-efeb23d8522a/lambda_function.zip

      - name: Update Lambda Function
        run: |
          aws lambda update-function-code --function-name automatedTradingScript --s3-bucket auto-trading-bucket --s3-key 1790ffe7-7b30-4e22-a488-efeb23d8522a/lambda_function.zip
